In [2]:
import pandas as pd
from scipy.stats import ttest_ind,ttest_rel,ttest_1samp

#Meron bang pagkakaiba sa dalawang way of study ng student na nakakaapektp sa exam score nila?
df = pd.read_csv('exam_scores.csv')

In [4]:
df.head(10)

   Student  With_Music  Without_Music
0        1          85             78
1        2          88             80
2        3          90             75
3        4          82             77
4        5          91             79
5        6          87             74
6        7          89             81
7        8          84             76
8        9          92             78
9       10          86             73

In [5]:
#Calaculate t-test and a p-value
t_test,p_value = ttest_ind(df['With_Music'],df['Without_Music'])

print('T_Stats: ',t_test)
print('P_value: ',p_value)

T_Stats:  10.84140689865639
P_value:  1.5707917380085374e-11

In [9]:
df.describe()

         Student  With_Music  Without_Music
count  15.000000   15.000000      15.000000
mean    8.000000   87.666667      77.200000
std     4.472136    2.894987       2.366432
min     1.000000   82.000000      73.000000
25%     4.500000   85.500000      75.500000
50%     8.000000   88.000000      77.000000
75%    11.500000   90.000000      79.000000
max    15.000000   92.000000      81.000000