MEASURE OF CENTRAL TENDENCY
 -Mahalaga ang Central Tendency (Mean, Median, Mode, Min, Max) nagbibigay ito ng isang representative value ng buong dataset. Sa halip na tingnan ang lahat ng data points isa-isa, makikita mo agad kung ano ang "karaniwang" value sa dataset

In [2]:
import pandas as pd

df = pd.read_csv('students_exam_scores.csv')
df

   Student_ID  Exam_Score
0          S1          45
1          S2          52
2          S3          60
3          S4          65
4          S5          70
5          S6          70
6          S7          72
7          S8          75
8          S9          80
9         S10          85
10        S11          90
11        S12          95
12        S13          70
13        S14          68
14        S15          74

In [5]:
#Average Exam Score
print(f'Average exam score: {df['Exam_Score'].mean()}')

Average exam score: 71.4

In [16]:
#Madalas na Score
print(f'Most frequent exam score: {df['Exam_Score'].mode()}')

Most frequent exam score: 0    70
Name: Exam_Score, dtype: int64

In [19]:
#Pinaka mababang Score
print(f'Minimum exam score: {df['Exam_Score'].min()}')

Minimum exam score: 45

In [18]:
#Pinaka Mataas na score
print(f'Maximum exam score: {df['Exam_Score'].max()}')

Maximum exam score: 95

In [15]:
df.describe()

       Exam_Score
count   15.000000
mean    71.400000
std     13.211467
min     45.000000
25%     66.500000
50%     70.000000
75%     77.500000
max     95.000000